services:
  - type: web
    name: tranquil-app
    env: node
    plan: free
    buildCommand: npm install && vite build && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist && node postbuild.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health